import operator
from typing import Annotated, TypedDict, List, Optional, Union

from langchain_core.messages import BaseMessage

class AgentState(TypedDict):
    """The state of the ARGOS agent swarm."""
    
    # The conversation history with the user/system
    messages: Annotated[List[BaseMessage], operator.add]
    
    # The next node to execute
    next: str
    
    # List of errors encountered during execution (for self-healing)
    errors: Annotated[List[str], operator.add]
    
    # The current code patch/diff generated by the Fixer
    code_diff: Optional[str]
    
    # Human-in-the-Loop status
    approval_status: str  # "PENDING", "APPROVED", "REJECTED", "NONE"
    
    # Execution logs from the sandbox
    logs: Annotated[List[str], operator.add]
